tree_kinematics_node:

  q_dot_max_factor: 1.000

  x_dot_trans_max: 1.000
  x_dot_rot_max: 1.000
  
  lambda: 0.01

  js_w_matr/j0:  0.0
  js_w_matr/j1:  0.0
  js_w_matr/j2:  0.0
  js_w_matr/j3:  0.0
  js_w_matr/j4:  1.0
  js_w_matr/j5:  1.0
  js_w_matr/j6:  1.0
  js_w_matr/j7:  1.0
  js_w_matr/j8:  1.0
  js_w_matr/j9:  1.0
  js_w_matr/j10: 1.0
  js_w_matr/j11: 1.0
  js_w_matr/j12: 1.0
  js_w_matr/j13: 1.0
  js_w_matr/j14: 1.0
  js_w_matr/j15: 1.0
  js_w_matr/j16: 1.0
  js_w_matr/j17: 1.0
  js_w_matr/j18: 1.0
  js_w_matr/j19: 1.0
  js_w_matr/j20: 1.0
  js_w_matr/j21: 1.0
  js_w_matr/j22: 1.0
  js_w_matr/j23: 1.0

  ts_w_matr/endpt0/px: 0.0
  ts_w_matr/endpt0/py: 0.0 
  ts_w_matr/endpt0/pz: 0.0
  ts_w_matr/endpt0/rx: 0.0
  ts_w_matr/endpt0/ry: 0.0
  ts_w_matr/endpt0/rz: 0.0

  ts_w_matr/endpt1/px: 0.0
  ts_w_matr/endpt1/py: 0.0
  ts_w_matr/endpt1/pz: 0.0
  ts_w_matr/endpt1/rx: 0.5
  ts_w_matr/endpt1/ry: 0.5
  ts_w_matr/endpt1/rz: 0.5

  ts_w_matr/endpt2/px: 1.0
  ts_w_matr/endpt2/py: 1.0
  ts_w_matr/endpt2/pz: 1.0
  ts_w_matr/endpt2/rx: 1.0
  ts_w_matr/endpt2/ry: 1.0
  ts_w_matr/endpt2/rz: 1.0

  ts_w_matr/endpt3/px: 0.0
  ts_w_matr/endpt3/py: 0.0
  ts_w_matr/endpt3/pz: 0.0
  ts_w_matr/endpt3/rx: 0.0
  ts_w_matr/endpt3/ry: 0.0
  ts_w_matr/endpt3/rz: 0.0

  ts_w_matr/endpt4/px: 0.0
  ts_w_matr/endpt4/py: 0.0
  ts_w_matr/endpt4/pz: 0.0
  ts_w_matr/endpt4/rx: 0.5
  ts_w_matr/endpt4/ry: 0.5
  ts_w_matr/endpt4/rz: 0.5

  ts_w_matr/endpt5/px: 1.0
  ts_w_matr/endpt5/py: 1.0
  ts_w_matr/endpt5/pz: 1.0
  ts_w_matr/endpt5/rx: 1.0
  ts_w_matr/endpt5/ry: 1.0
  ts_w_matr/endpt5/rz: 1.0

  ts_w_matr/endpt6/px: 0.0
  ts_w_matr/endpt6/py: 0.0
  ts_w_matr/endpt6/pz: 0.0
  ts_w_matr/endpt6/rx: 0.0
  ts_w_matr/endpt6/ry: 1.0
  ts_w_matr/endpt6/rz: 1.0

  ts_w_matr/endpt7/px: 0.0
  ts_w_matr/endpt7/py: 0.0
  ts_w_matr/endpt7/pz: 0.0
  ts_w_matr/endpt7/rx: 0.0
  ts_w_matr/endpt7/ry: 1.0
  ts_w_matr/endpt7/rz: 1.0
  
tree_joint_controller:

  type: tree_joint_controller/TreeJointController

  robot_description: /robot_description

  limit_error: true

  q_err_max: 0.01
  q_err_dot_max_factor: 2.0

  PGain: 2000.0
  DGain: 1000.0
  DGainFactor: 0.7
  
  Kp_0:  0.5
  Kp_1:  0.5
  Kp_2:  0.5
  Kp_3:  0.5
  Kp_4:  1.5
  Kp_5:  1.5
  Kp_6:  1.0
  Kp_7:  1.0
  Kp_8:  0.9
  Kp_9:  0.9
  Kp_10: 0.6
  Kp_11: 0.6
  Kp_12: 0.6
  Kp_13: 1.0
  Kp_14: 1.0
  Kp_15: 0.9
  Kp_16: 0.9
  Kp_17: 0.6
  Kp_18: 0.6
  Kp_19: 0.6
  Kp_20: 0.6
  Kp_21: 0.6

  Kd_0:  0.5
  Kd_1:  0.5
  Kd_2:  0.5
  Kd_3:  0.5
  Kd_4:  1.5
  Kd_5:  1.5
  Kd_6:  1.0
  Kd_7:  1.0
  Kd_8:  0.9
  Kd_9:  0.9
  Kd_10: 0.6
  Kd_11: 0.6
  Kd_12: 0.6
  Kd_13: 1.0
  Kd_14: 1.0
  Kd_15: 0.9
  Kd_16: 0.9
  Kd_17: 0.6
  Kd_18: 0.6
  Kd_19: 0.6
  Kd_20: 0.6
  Kd_21: 0.6

