motion_adaption_node:

  wait_for_tf_in_sec:             0.5
  world_ref_frame_name:           /openni_depth_optical_frame
  user:
    torso_frame_name:             /torso
    head_frame_name:              /head
    right_shoulder_frame_name:    /right_shoulder
    right_elbow_frame_name:       /right_elbow
    right_hand_frame_name:        /right_hand
    left_shoulder_frame_name:     /left_shoulder
    left_elbow_frame_name:        /left_elbow
    left_hand_frame_name:         /left_hand
  robot:
    base_frame_name:              /base_link
    torso_ref_frame_name:         /torso_1_link

    head_frame_name:              /head_2_link    
    right_shoulder_frame_name:    /arm_right_2_link
    right_elbow_frame_name:       /arm_right_4_link
    right_hand_frame_name:        /palm_right_link    
    left_shoulder_frame_name:     /arm_left_2_link
    
  # define roations of orientations by roll pitch yaw
  rotation_angles:
    # align the orientation of the user torso with robot torso
    # i.e.: user bends foward -> ref frame rotates forward
    ref_frame_rot:
      r:                        rad(0.5 * pi)
      p:                        0.0
      y:                        rad(0.5 * -pi)
    # align adapted frames with goal frames
    goals:
      torso_goal_rot:
        r:                      rad(pi)
        p:                      rad(0.5 * pi)
        y:                      0.0
      head_goal_rot:
        r:                      rad(pi)
        p:                      rad(0.5 * pi)
        y:                      0.0
      right_elbow_goal_rot:
        r:                      rad(pi)
        p:                      0.0
        y:                      rad(pi)
      right_hand_goal_rot:
        r:                      0.0
        p:                      rad(0.5 * pi)
        y:                      0.0
      left_elbow_goal_rot:
        r:                      0.0
        p:                      rad(pi)
        y:                      0.0
      left_hand_goal_rot:
        r:                      0.0
        p:                      rad(0.5 * -pi)
        y:                      0.0    

#----------------------------------------------------------------------------------------------------------------------#

reem_teleop_coordinator_node:

  nr_of_endpoints:      6
  endpoint_0:           torso_2_link
  endpoint_1:           head_2_link
  endpoint_2:           arm_right_4_link
  endpoint_3:           palm_right_link
  endpoint_4:           arm_left_4_link
  endpoint_5:           palm_left_link
  endpoint_0_goal:      torso_goal
  endpoint_1_goal:      head_goal
  endpoint_2_goal:      r_elbow_goal
  endpoint_3_goal:      r_hand_goal
  endpoint_4_goal:      l_elbow_goal
  endpoint_5_goal:      l_hand_goal
  root_frame_name:      ref_frame
  
  check_self_collision: true
  check_joint_limits:   false  

  loop_rate: 10
  
#----------------------------------------------------------------------------------------------------------------------#

tree_kinematics_node:

  urdf_xml_model:       robot_description

  nr_of_endpoints:      6
  endpoint_0:           torso_2_link
  endpoint_1:           head_2_link
  endpoint_2:           arm_right_4_link
  endpoint_3:           palm_right_link
  endpoint_4:           arm_left_4_link
  endpoint_5:           palm_left_link

  # frequency of the service calls for IK calculations in hz
  # used to calculate velocities and to adapt the maximum velocties specified below
  srv_call_frequency: 10
  
  # the precision of the endeffectors position the IK solver tries to reach
  epsilon: 0.010
  
  # the maximum number of iterations the IK solver will execute
  max_iterations: 10

  # Factor applied to the maximum velocities specified in the urdf model of the robot in rad/sec
  q_dot_max_factor: 1.0
  q_dot_min_factor: 0.0
  
  low_pass_factor:  1.0

  # minimum and maximum translational and rotational velocities of the endeffectors in m/sec
  x_dot_trans_min: 1.0
  x_dot_trans_max: 1.0
  x_dot_rot_min: 3.14
  x_dot_rot_max: 3.14
    
  # Factor to prevent running through kinematic singularities
  lambda: 0.01

  js_w_matr/j0:  0.0
  js_w_matr/j1:  0.0
  js_w_matr/j2:  0.0
  js_w_matr/j3:  0.0
  js_w_matr/j4:  1.0
  js_w_matr/j5:  1.0
  js_w_matr/j6:  1.0
  js_w_matr/j7:  1.0
  js_w_matr/j8:  1.0
  js_w_matr/j9:  1.0
  js_w_matr/j10: 1.0
  js_w_matr/j11: 1.0
  js_w_matr/j12: 1.0
  js_w_matr/j13: 1.0
  js_w_matr/j14: 1.0
  js_w_matr/j15: 1.0
  js_w_matr/j16: 1.0
  js_w_matr/j17: 1.0
  js_w_matr/j18: 1.0
  js_w_matr/j19: 1.0
  js_w_matr/j20: 1.0
  js_w_matr/j21: 1.0
  js_w_matr/j22: 1.0
  js_w_matr/j23: 1.0

  ts_w_matr/endpt0/px: 0.2
  ts_w_matr/endpt0/py: 0.2
  ts_w_matr/endpt0/pz: 0.2
  ts_w_matr/endpt0/rx: 0.2
  ts_w_matr/endpt0/ry: 0.2
  ts_w_matr/endpt0/rz: 0.2

  ts_w_matr/endpt1/px: 1.0
  ts_w_matr/endpt1/py: 1.0
  ts_w_matr/endpt1/pz: 1.0
  ts_w_matr/endpt1/rx: 1.0
  ts_w_matr/endpt1/ry: 1.0
  ts_w_matr/endpt1/rz: 1.0

  ts_w_matr/endpt2/px: 0.2
  ts_w_matr/endpt2/py: 0.2
  ts_w_matr/endpt2/pz: 0.2
  ts_w_matr/endpt2/rx: 0.2
  ts_w_matr/endpt2/ry: 0.2
  ts_w_matr/endpt2/rz: 0.2

  ts_w_matr/endpt3/px: 1.0
  ts_w_matr/endpt3/py: 1.0
  ts_w_matr/endpt3/pz: 1.0
  ts_w_matr/endpt3/rx: 1.0
  ts_w_matr/endpt3/ry: 1.0
  ts_w_matr/endpt3/rz: 1.0

  ts_w_matr/endpt4/px: 0.0
  ts_w_matr/endpt4/py: 0.0
  ts_w_matr/endpt4/pz: 0.0
  ts_w_matr/endpt4/rx: 0.0
  ts_w_matr/endpt4/ry: 1.0
  ts_w_matr/endpt4/rz: 1.0

  ts_w_matr/endpt5/px: 0.0
  ts_w_matr/endpt5/py: 0.0
  ts_w_matr/endpt5/pz: 0.0
  ts_w_matr/endpt5/rx: 0.0
  ts_w_matr/endpt5/ry: 1.0
  ts_w_matr/endpt5/rz: 1.0

#----------------------------------------------------------------------------------------------------------------------#

joint_position_controller:

  type: joint_position_controller/JointPositionController

  robot_description: /robot_description

  limit_error: false

  q_err_max: 0.01
  q_err_dot_max_factor: 2.0

  PGain: 500.0
  DGain: 200000.0
  DGainFactor: 0.7
  
  Kp_0:  0.5
  Kp_1:  0.5
  Kp_2:  0.5
  Kp_3:  0.5
  Kp_4:  1.5
  Kp_5:  1.5
  Kp_6:  1.0
  Kp_7:  1.0
  Kp_8:  0.9
  Kp_9:  0.9
  Kp_10: 0.6
  Kp_11: 0.6
  Kp_12: 0.6
  Kp_13: 1.0
  Kp_14: 1.0
  Kp_15: 0.9
  Kp_16: 0.9
  Kp_17: 0.6
  Kp_18: 0.6
  Kp_19: 0.6
  Kp_20: 0.6
  Kp_21: 0.6

  Kd_0:  0.5
  Kd_1:  0.5
  Kd_2:  0.5
  Kd_3:  0.5
  Kd_4:  1.5
  Kd_5:  1.5
  Kd_6:  1.0
  Kd_7:  1.0
  Kd_8:  0.9
  Kd_9:  0.9
  Kd_10: 0.6
  Kd_11: 0.6
  Kd_12: 0.6
  Kd_13: 1.0
  Kd_14: 1.0
  Kd_15: 0.9
  Kd_16: 0.9
  Kd_17: 0.6
  Kd_18: 0.6
  Kd_19: 0.6
  Kd_20: 0.6
  Kd_21: 0.6
  
  tau_max_value: 80.0
  tau_max_factor_0:  0.0
  tau_max_factor_1:  0.0
  tau_max_factor_2:  0.0
  tau_max_factor_3:  0.0
  tau_max_factor_4:  1.5
  tau_max_factor_5:  1.5
  tau_max_factor_6:  1.0
  tau_max_factor_7:  1.0
  tau_max_factor_8:  0.9
  tau_max_factor_9:  0.9
  tau_max_factor_10: 0.6
  tau_max_factor_11: 0.6
  tau_max_factor_12: 0.6
  tau_max_factor_13: 1.0
  tau_max_factor_14: 1.0
  tau_max_factor_15: 0.9
  tau_max_factor_16: 0.9
  tau_max_factor_17: 0.6
  tau_max_factor_18: 0.6
  tau_max_factor_19: 0.6
  tau_max_factor_20: 0.6
  tau_max_factor_21: 0.6
  tau_max_factor_22: 0.5
  tau_max_factor_23: 0.5
  
